# Generated by Django 4.1.2 on 2023-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
